language: android

before_install:
  - pip install codecov

after_success:
  - codecov
  # - bash <(curl -s https://codecov.io/bash)

jdk:
    - oraclejdk8

android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support

notifications:
    email:
        - alessandro.crugnola@gmail.com

cache: false
sudo: false

install:
    # Ensure Gradle wrapper is executable, download wrapper and show version
    - chmod +x ./gradlew; ls -l gradlew; ./gradlew wrapper -v

    # Download and show android dependencies
    - ./gradlew androidDependencies

script:
  - sh ci.sh
  - ./gradlew bottom-navigation:connectedCheck bottom-navigation:assemble

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle